import { useEffect, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { Icon } from '../lib/icons'

/* The calendar beat — the orb has become operational. A real calendar sits in
   the centre; an animated cursor selects actions from the orb's suggestions and
   you watch the calendar update: a follow-up drops in with a reminder, then a
   reply is drafted, then everything commits to memory. Show, don't tell. */

const EASE = [0.2, 0.8, 0.2, 1] as const

const ACTIONS = ['Summarise', 'Draft Reply', 'Schedule Meeting', 'Add Follow-up']
const ROW_Y = [52, 88, 124, 160]
const CURSOR = { x: 130, y: 124 }

const DAYS = [['Mon', 16], ['Tue', 17], ['Wed', 18], ['Thu', 19], ['Fri', 20]] as const
const TIMES = ['10', '11', '12', '1', '2', '3']
// existing events: [dayIndex, timeIndex, label, tone]
const EVENTS: [number, number, string, string][] = [
  [0, 0, 'Standup', ''],
  [1, 1, 'Acme call', 'next'],
  [3, 3, 'Northwind', ''],
]

function CalendarGrid({ scheduled }: { scheduled: boolean }) {
  return (
    <div className="os-cal-grid">
      <div className="cg-head"><span className="cg-title">March 2026</span><span className="cg-now"><span className="pdot" /> Tue · 11:16</span></div>
      <div className="cg-grid">
        <span className="cg-corner" />
        {DAYS.map(([d, n]) => (
          <span className="cg-dh" key={d}><b>{d}</b><i>{n}</i></span>
        ))}
        {TIMES.map((t, r) => (
          <span className="cg-tl" key={t} style={{ gridColumn: 1, gridRow: r + 2 }}>{t}</span>
        ))}
        {TIMES.map((_, r) => DAYS.map((_, c) => (
          <span className="cg-slot" key={`${r}-${c}`} style={{ gridColumn: c + 2, gridRow: r + 2 }} />
        )))}
        {EVENTS.map(([c, r, label, tone]) => (
          <span className={'cg-ev ' + tone} key={label} style={{ gridColumn: c + 2, gridRow: r + 2 }}>{label}</span>
        ))}
        <AnimatePresence>
          {scheduled && (
            <motion.span
              className="cg-ev added" style={{ gridColumn: 3, gridRow: 6 }}
              initial={{ opacity: 0, scale: 0.6 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0 }}
              transition={{ duration: 0.5, ease: EASE }}
            >Follow-up<span className="cg-added">added</span></motion.span>
          )}
        </AnimatePresence>
      </div>
    </div>
  )
}

export default function CalendarStage({ reduce }: { reduce: boolean }) {
  // step: 0 panel in · 1 →schedule · 2 click+calendar · 3 →email · 4 click+draft · 5 committed
  const [step, setStep] = useState(reduce ? 5 : 0)

  useEffect(() => {
    if (reduce) return
    const at = [600, 1500, 2400, 3300, 4300]
    const ts = at.map((ms, i) => window.setTimeout(() => setStep(i + 1), ms))
    return () => ts.forEach(clearTimeout)
  }, [reduce])

  const done = (i: number) => (i === 2 && step >= 2) || (i === 1 && step >= 4)
  const cursorTo = step >= 3 ? { x: 130, y: ROW_Y[1] } : step >= 1 ? { x: 130, y: ROW_Y[2] } : CURSOR
  const clicking = step === 2 || step === 4

  return (
    <>
      <CalendarGrid scheduled={step >= 2} />

      <div className="os-act">
        <div className="os-act-panel">
          <div className="os-act-h"><span className="os-act-orbdot" /> Generated by Noise</div>
          {ACTIONS.map((a, i) => (
            <motion.div
              className={'os-act-row' + (done(i) ? ' done' : '')}
              key={a}
              initial={reduce ? false : { opacity: 0, y: -26 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, ease: EASE, delay: reduce ? 0 : 0.15 + i * 0.12 }}
            >
              <span className="os-act-tick">{done(i) ? Icon.check : null}</span>
              {a}
            </motion.div>
          ))}
          {!reduce && (
            <motion.div
              className={'os-cursor' + (clicking ? ' click' : '')}
              initial={{ opacity: 0, x: CURSOR.x, y: CURSOR.y }}
              animate={{ opacity: step >= 1 && step < 5 ? 1 : 0, x: cursorTo.x, y: cursorTo.y }}
              transition={{ duration: 0.7, ease: EASE }}
            >
              <svg viewBox="0 0 24 24"><path d="M5 3l15 9-6 1.5L11 20 5 3z" /></svg>
            </motion.div>
          )}
        </div>

        <div className="os-act-results">
          <AnimatePresence>
            {step >= 4 && (
              <motion.div className="os-act-card" key="mail"
                initial={reduce ? false : { opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} transition={{ duration: 0.5, ease: EASE }}>
                <div className="os-ac-row">
                  <span className="os-ac-ic">{Icon.mail}</span><div className="os-ac-t">Reply to Sarah</div>
                  <span className={'os-ac-status' + (step >= 5 ? ' sent' : '')}>{step >= 5 ? <>{Icon.check} Sent</> : 'Drafting…'}</span>
                </div>
                <div className="os-ac-body">Hi Sarah — I’ve scheduled a follow-up for Tuesday and attached the renewal summary. Let me know if another time works better.</div>
              </motion.div>
            )}
            {step >= 5 && (
              <motion.div className="os-act-commit" key="commit"
                initial={reduce ? false : { opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.5, staggerChildren: 0.12 }}>
                {['Stored in memory', 'Relationship updated'].map((c) => (
                  <motion.span className="os-commit" key={c} initial={reduce ? false : { opacity: 0, x: -8 }} animate={{ opacity: 1, x: 0 }}>
                    {Icon.check} {c}
                  </motion.span>
                ))}
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </>
  )
}
